Change spaces to tabs in kpatch-0.9.1-downgrade-patch-dry-run-from-die-to-warn.patch

diff --git a/sys-kernel/kpatch/files/kpatch-0.9.1-downgrade-patch-dry-run-from-die-to-warn.patch b/sys-kernel/kpatch/files/kpatch-0.9.1-downgrade-patch-dry-run-from-die-to-warn.patch
--- a/sys-kernel/kpatch/files/kpatch-0.9.1-downgrade-patch-dry-run-from-die-to-warn.patch
+++ b/sys-kernel/kpatch/files/kpatch-0.9.1-downgrade-patch-dry-run-from-die-to-warn.patch
@@ -39,7 +39,7 @@ diff -urp kpatch-0.9.1.orig/kpatch-build/kpatch-build kpatch-0.9.1/kpatch-build/
  	echo "		--skip-cleanup     Skip post-build cleanup" >&2
  	echo "		--skip-gcc-check   Skip gcc version matching check" >&2
  	echo "		                   (not recommended)" >&2
-+	echo "          --no-dry-run-dies  Downgrade patch dry-run failure from die to warn" >&2
++	echo "		--no-dry-run-dies  Downgrade patch dry-run failure from die to warn" >&2
  }
  
 -options="$(getopt -o ha:r:s:c:v:j:t:n:o:de: -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,oot-module:,debug,skip-gcc-check,skip-cleanup" -- "$@")" || die "getopt failed"
