Prevent duplication of amdgpu-pro{,-lts} paths in LDPATH and 20opengl.conf in eselect-opengl with amdgpu-pro-support patch

diff --git a/app-eselect/eselect-opengl/files/eselect-opengl-1.3.1-amdgpu-pro-support.patch b/app-eselect/eselect-opengl/files/eselect-opengl-1.3.1-amdgpu-pro-support.patch
--- a/app-eselect/eselect-opengl/files/eselect-opengl-1.3.1-amdgpu-pro-support.patch
+++ b/app-eselect/eselect-opengl/files/eselect-opengl-1.3.1-amdgpu-pro-support.patch
@@ -1,5 +1,5 @@
---- a/opengl.eselect-1.3.1.orig	2020-04-30 20:21:51.712174821 -0700
-+++ b/opengl.eselect-1.3.1	2020-04-30 20:36:07.295212666 -0700
+--- opengl.eselect-1.3.1.orig	2020-04-30 22:00:14.065337515 -0700
++++ opengl.eselect-1.3.1	2020-04-30 22:50:29.720673114 -0700
 @@ -9,6 +9,7 @@
  # Further modifications based off submissions to bug #54984 <cyfred@gentoo.org>
  # Further modifications by Jeremy Huddleston <eradicator@gentoo.org>
@@ -36,66 +36,54 @@
  			[[ -d ${PREFIX}/${libdir}/opengl && ! -h ${PREFIX}/${libdir} ]] || continue
  			[[ -f "${PREFIX}/${libdir}/opengl/${gl_implem}/lib/libGL.so" || -f "${PREFIX}/${libdir}/opengl/${gl_implem}/.gles-only" ]] && found_libgl=yes
  		done
-@@ -116,9 +131,59 @@ set_new_implementation() {
+@@ -112,6 +127,50 @@ set_new_implementation() {
+ 		rm -f "${XORGD_FILE}" || die -q "Failed to remove ${ENV_FILE}"
+ 	fi
+ 
++	# For amdgpu-pro-lts (pro-stack)
++	if [[ -d "${EROOT}/opt/amdgpu-pro/lib/xorg/modules" ]] ; then
++		xorgmodpath+=(
++			"${EROOT}/opt/amdgpu-pro/lib/xorg/modules"
++		)
++	fi
++
++	# For amdgpu-pro-lts (open-stack)
++	if [[ -d "${EROOT}/opt/amdgpu/lib/xorg/modules" ]] ; then
++		xorgmodpath+=(
++			"${EROOT}/opt/amdgpu/lib/xorg/modules"
++		)
++	fi
++
++	# For amdgpu-pro (pro-stack)
++	if [[ -d "${EROOT}/opt/amdgpu-pro/lib64/xorg/modules" ]] ; then
++		xorgmodpath+=(
++			"${EROOT}/opt/amdgpu-pro/lib64/xorg/modules"
++		)
++	fi
++
++	# For amdgpu-pro (open-stack)
++	if [[ -d "${EROOT}/opt/amdgpu/lib64/xorg/modules" ]] ; then
++		xorgmodpath+=(
++			"${EROOT}/opt/amdgpu/lib64/xorg/modules"
++		)
++	fi
++
++	if [[ -d "${EROOT}/opt/amdgpu-pro/lib/x86_64-linux-gnu" ]] ; then
++		ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu-pro/lib/x86_64-linux-gnu
++	fi
++	if [[ -d "${EROOT}/opt/amdgpu-pro/lib/i386-linux-gnu" ]] ; then
++		ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu-pro/lib/i386-linux-gnu
++	fi
++	if [[ -d "${EROOT}/opt/amdgpu/lib/x86_64-linux-gnu" ]] ; then
++		ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu/lib/x86_64-linux-gnu
++	fi
++	if [[ -d "${EROOT}/opt/amdgpu/lib/i386-linux-gnu" ]] ; then
++		ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu/lib/i386-linux-gnu
++	fi
++	if [[ -d "${EROOT}/opt/amdgpu-pro/lib64" ]] ; then
++		ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu-pro/lib64
++	fi
++
+ 	for libdir in $(list_libdirs); do
  		# Set libdir correctly to EROOT
  		[[ ${ROOT} != / ]] && libdir=${libdir#${EROOT}}
- 
--		# First make sure we have an opengl directory and this
--		# is a real lib dir, not a symlink
--		[[ -d ${PREFIX}/${libdir}/opengl && ! -h ${PREFIX}/${libdir} ]] || continue
-+		# For amdgpu-pro-lts (pro-stack)
-+		if [[ -d "${EROOT}/opt/amdgpu-pro/lib/xorg/modules" ]] ; then
-+			if [[ "${libdir}" == "lib64" ]] ; then
-+				ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu-pro/lib/x86_64-linux-gnu
-+			elif [[ "${libdir}" == "lib32" ]] ; then
-+				ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu-pro/lib/i386-linux-gnu
-+			fi
-+			xorgmodpath+=(
-+				"${EROOT}/opt/amdgpu-pro/lib/xorg/modules"
-+			)
-+		fi
-+		# For amdgpu-pro-lts (open-stack)
-+		if [[ -d "${EROOT}/opt/amdgpu/lib/xorg/modules" ]] ; then
-+			if [[ "${libdir}" == "lib64" ]] ; then
-+				ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu/lib/x86_64-linux-gnu
-+			elif [[ "${libdir}" == "lib32" ]] ; then
-+				ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu/lib/i386-linux-gnu
-+			fi
-+			xorgmodpath+=(
-+				"${EROOT}/opt/amdgpu/lib/xorg/modules"
-+			)
-+		fi
-+
-+		# For amdgpu-pro (pro-stack)
-+		if [[ -d "${EROOT}/opt/amdgpu-pro/lib64/xorg/modules" ]] ; then
-+			if [[ "${libdir}" == "lib64" ]] ; then
-+				ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu-pro/lib64
-+			fi
-+			xorgmodpath+=(
-+				"${EROOT}/opt/amdgpu-pro/lib64/xorg/modules"
-+			)
-+		fi
-+		# For amdgpu-pro (open-stack)
-+		if [[ -d "${EROOT}/opt/amdgpu/lib64/xorg/modules" ]] ; then
-+			if [[ "${libdir}" == "lib64" ]] ; then
-+				ldpath=${ldpath:+${ldpath}:}${EROOT}/opt/amdgpu-pro/lib64
-+			fi
-+			xorgmodpath+=(
-+				"${EROOT}/opt/amdgpu/lib64/xorg/modules"
-+			)
-+		fi
-+
-+		if [[ -d "${EROOT}/opt/amdgpu-pro/lib/xorg/modules" \
-+			|| -d "${EROOT}/opt/amdgpu/lib/xorg/modules" \
-+			|| -d "${EROOT}/opt/amdgpu-pro/lib64/xorg/modules" \
-+			|| -d "${EROOT}/opt/amdgpu/lib64/xorg/modules" ]]
-+		then
-+			:;
-+		else
-+			# First make sure we have an opengl directory and this
-+			# is a real lib dir, not a symlink
-+			[[ -d ${PREFIX}/${libdir}/opengl && ! -h ${PREFIX}/${libdir} ]] || continue
-+		fi
- 
- 		# Check if opengl implementation directory exists
- 		# and use xorg-x11 as fallback (mesa)
