Update patches in patch for hip ebuild

diff --git a/dev-util/hip/files/roctracer-5.1.3-path-changes.patch b/dev-util/hip/files/roctracer-5.1.3-path-changes.patch
--- a/dev-util/hip/files/roctracer-5.1.3-path-changes.patch
+++ b/dev-util/hip/files/roctracer-5.1.3-path-changes.patch
@@ -1,6 +1,6 @@
 diff -urp roctracer-rocm-5.1.3.orig/CMakeLists.txt roctracer-rocm-5.1.3/CMakeLists.txt
 --- roctracer-rocm-5.1.3.orig/CMakeLists.txt	2022-04-18 06:49:13.000000000 -0700
-+++ roctracer-rocm-5.1.3/CMakeLists.txt	2023-08-22 19:12:20.391977217 -0700
++++ roctracer-rocm-5.1.3/CMakeLists.txt	2023-09-19 18:57:31.568945829 -0700
 @@ -124,14 +124,14 @@ message ( "-----------CPACK-dir: ${CPACK
  #add_custom_target ( inc-link ALL WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
  #                    COMMAND ${CMAKE_COMMAND} -E create_symlink ../${DEST_NAME}/include inc-link )
@@ -59,7 +59,7 @@ diff -urp roctracer-rocm-5.1.3.orig/CMakeLists.txt roctracer-rocm-5.1.3/CMakeLis
  set ( CPACK_GENERATOR "DEB" "RPM" "TGZ" CACHE STRING "CPACK GENERATOR DEB;RPM")
 diff -urp roctracer-rocm-5.1.3.orig/README.md roctracer-rocm-5.1.3/README.md
 --- roctracer-rocm-5.1.3.orig/README.md	2022-04-18 06:49:13.000000000 -0700
-+++ roctracer-rocm-5.1.3/README.md	2023-08-22 19:11:10.999975495 -0700
++++ roctracer-rocm-5.1.3/README.md	2023-09-19 18:57:31.756945827 -0700
 @@ -15,13 +15,13 @@ Includes basic API: roctxMark, roctxRang
  ```
  rocTracer API:
@@ -80,7 +80,7 @@ diff -urp roctracer-rocm-5.1.3.orig/README.md roctracer-rocm-5.1.3/README.md
  ## The library source tree
 diff -urp roctracer-rocm-5.1.3.orig/test/hsa/script/build_kernel.sh roctracer-rocm-5.1.3/test/hsa/script/build_kernel.sh
 --- roctracer-rocm-5.1.3.orig/test/hsa/script/build_kernel.sh	2022-04-18 06:49:13.000000000 -0700
-+++ roctracer-rocm-5.1.3/test/hsa/script/build_kernel.sh	2023-08-22 19:11:09.847975466 -0700
++++ roctracer-rocm-5.1.3/test/hsa/script/build_kernel.sh	2023-09-19 19:01:00.528943039 -0700
 @@ -32,9 +32,9 @@ fi
  
  OCL_VER="2.0"
@@ -88,9 +88,27 @@ diff -urp roctracer-rocm-5.1.3.orig/test/hsa/script/build_kernel.sh roctracer-ro
 -if [ -e $ROCM_DIR/llvm ] ; then
 -  LLVM_DIR=$ROCM_DIR/llvm
 -  LIB_DIR=$ROCM_DIR/lib
-+if [ -e $ROCM_DIR/lib/llvm/@LLVM_SLOT@ ] ; then
-+  LLVM_DIR=$ROCM_DIR/lib/llvm/@LLVM_SLOT@
++if [ -e @ESYSROOT_LLVM_PATH@ ] ; then
++  LLVM_DIR=@ESYSROOT_LLVM_PATH@
 +  LIB_DIR=$ROCM_DIR/@LIBDIR@
  else
    LLVM_DIR=$ROCM_DIR/hcc
    LIB_DIR=$LLVM_DIR/lib
+@@ -45,6 +45,8 @@ if [ -e $LIB_DIR/bitcode/opencl.amdgcn.b
+   BC_DIR=$LIB_DIR/bitcode
+ elif [ -e $LIB_DIR/opencl.amdgcn.bc ]; then
+   BC_DIR=$LIB_DIR
++elif [ -e $ROCM_DIR/@LIBDIR@/amdgcn/bitcode/opencl.bc ]; then
++  BC_DIR=$ROCM_DIR/@LIBDIR@/amdgcn/bitcode
+ elif [ -e $ROCM_DIR/amdgcn/bitcode/opencl.bc ]; then
+   BC_DIR=$ROCM_DIR/amdgcn/bitcode
+ else
+@@ -52,7 +54,7 @@ else
+   exit 1
+ fi
+ 
+-CLANG_ROOT=$LLVM_DIR/lib/clang
++CLANG_ROOT=$LLVM_DIR/@LIBDIR@/clang
+ CLANG_DIR=`ls -d $CLANG_ROOT/* | head -n 1`
+ if [ "$CLANG_DIR" = "" ] ; then
+   echo "Error: LLVM clang library was not found"
